[project]
name = "salvia37site"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "invoke>=2.2.0",
    "markdown>=3.9",
    "pelican>=4.11.0",
]
